/* LinguaCore v0.9.0 — course data */
const COURSE_DATA = {
  spanish: [
    {"id": "es_a1_001", "level": "A1", "target": "hola", "pl": "cześć"},
    {"id": "es_a1_002", "level": "A1", "target": "adiós", "pl": "do widzenia"},
    {"id": "es_a1_003", "level": "A1", "target": "gracias", "pl": "dziękuję"},
    {"id": "es_a1_004", "level": "A1", "target": "por favor", "pl": "proszę"},
    {"id": "es_a1_005", "level": "A1", "target": "sí", "pl": "tak"},
    {"id": "es_a1_006", "level": "A1", "target": "no", "pl": "nie"},
    {"id": "es_a1_007", "level": "A1", "target": "buenos días", "pl": "dzień dobry"},
    {"id": "es_a1_008", "level": "A1", "target": "buenas noches", "pl": "dobranoc"},
    {"id": "es_a1_009", "level": "A1", "target": "¿cómo estás?", "pl": "jak się masz?"},
    {"id": "es_a1_010", "level": "A1", "target": "bien", "pl": "dobrze"},
    {"id": "es_a1_011", "level": "A1", "target": "mal", "pl": "źle"},
    {"id": "es_a1_012", "level": "A1", "target": "agua", "pl": "woda"},
    {"id": "es_a1_013", "level": "A1", "target": "comida", "pl": "jedzenie"},
    {"id": "es_a1_014", "level": "A1", "target": "casa", "pl": "dom"},
    {"id": "es_a1_015", "level": "A1", "target": "coche", "pl": "samochód"},
    {"id": "es_a1_016", "level": "A1", "target": "trabajo", "pl": "praca"},
    {"id": "es_a1_017", "level": "A1", "target": "familia", "pl": "rodzina"},
    {"id": "es_a1_018", "level": "A1", "target": "amigo", "pl": "przyjaciel"},
    {"id": "es_a1_019", "level": "A1", "target": "mujer", "pl": "kobieta"},
    {"id": "es_a1_020", "level": "A1", "target": "hombre", "pl": "mężczyzna"},
    {"id": "es_a1_021", "level": "A1", "target": "niño", "pl": "chłopiec"},
    {"id": "es_a1_022", "level": "A1", "target": "niña", "pl": "dziewczynka"},
    {"id": "es_a1_023", "level": "A1", "target": "día", "pl": "dzień"},
    {"id": "es_a1_024", "level": "A1", "target": "noche", "pl": "noc"},
    {"id": "es_a1_025", "level": "A1", "target": "hoy", "pl": "dzisiaj"},
    {"id": "es_a1_026", "level": "A1", "target": "mañana", "pl": "jutro"},
    {"id": "es_a1_027", "level": "A1", "target": "ayer", "pl": "wczoraj"},
    {"id": "es_a1_028", "level": "A1", "target": "ahora", "pl": "teraz"},
    {"id": "es_a1_029", "level": "A1", "target": "aquí", "pl": "tutaj"},
    {"id": "es_a1_030", "level": "A1", "target": "allí", "pl": "tam"},
    {"id": "es_a1_031", "level": "A1", "target": "grande", "pl": "duży"},
    {"id": "es_a1_032", "level": "A1", "target": "pequeño", "pl": "mały"},
    {"id": "es_a1_033", "level": "A1", "target": "bueno", "pl": "dobry"},
    {"id": "es_a1_034", "level": "A1", "target": "nuevo", "pl": "nowy"},
    {"id": "es_a1_035", "level": "A1", "target": "viejo", "pl": "stary"},
    {"id": "es_a1_036", "level": "A1", "target": "rápido", "pl": "szybki"},
    {"id": "es_a1_037", "level": "A1", "target": "lento", "pl": "wolny"},
    {"id": "es_a1_038", "level": "A1", "target": "comer", "pl": "jeść"},
    {"id": "es_a1_039", "level": "A1", "target": "beber", "pl": "pić"},
    {"id": "es_a1_040", "level": "A1", "target": "ir", "pl": "iść / jechać"},
    {"id": "es_a1_041", "level": "A1", "target": "venir", "pl": "przychodzić / przyjeżdżać"},
    {"id": "es_a1_042", "level": "A1", "target": "hablar", "pl": "mówić"},
    {"id": "es_a1_043", "level": "A1", "target": "escuchar", "pl": "słuchać"},
    {"id": "es_a1_044", "level": "A1", "target": "ver", "pl": "widzieć"},
    {"id": "es_a1_045", "level": "A1", "target": "leer", "pl": "czytać"},
    {"id": "es_a1_046", "level": "A1", "target": "escribir", "pl": "pisać"},
    {"id": "es_a1_047", "level": "A1", "target": "querer", "pl": "chcieć"},
    {"id": "es_a1_048", "level": "A1", "target": "tener", "pl": "mieć"},
    {"id": "es_a1_049", "level": "A1", "target": "hacer", "pl": "robić"},
    {"id": "es_a1_050", "level": "A1", "target": "comprar", "pl": "kupować"},
    {"id": "es_a1_051", "level": "A1", "target": "uno", "pl": "jeden"},
    {"id": "es_a1_052", "level": "A1", "target": "dos", "pl": "dwa"},
    {"id": "es_a1_053", "level": "A1", "target": "tres", "pl": "trzy"},
    {"id": "es_a1_054", "level": "A1", "target": "cuatro", "pl": "cztery"},
    {"id": "es_a1_055", "level": "A1", "target": "cinco", "pl": "pięć"},
    {"id": "es_a1_056", "level": "A1", "target": "calle", "pl": "ulica"},
    {"id": "es_a1_057", "level": "A1", "target": "tienda", "pl": "sklep"},
    {"id": "es_a1_058", "level": "A1", "target": "escuela", "pl": "szkoła"},
    {"id": "es_a1_059", "level": "A1", "target": "hotel", "pl": "hotel"},
    {"id": "es_a1_060", "level": "A1", "target": "aeropuerto", "pl": "lotnisko"},
    {"id": "es_a2_001", "level": "A2", "target": "siempre", "pl": "zawsze"},
    {"id": "es_a2_002", "level": "A2", "target": "nunca", "pl": "nigdy"},
    {"id": "es_a2_003", "level": "A2", "target": "a veces", "pl": "czasami"},
    {"id": "es_a2_004", "level": "A2", "target": "todavía", "pl": "nadal"},
    {"id": "es_a2_005", "level": "A2", "target": "ya", "pl": "już"},
    {"id": "es_a2_006", "level": "A2", "target": "pronto", "pl": "wkrótce"},
    {"id": "es_a2_007", "level": "A2", "target": "tarde", "pl": "późno"},
    {"id": "es_a2_008", "level": "A2", "target": "temprano", "pl": "wcześnie"},
    {"id": "es_a2_009", "level": "A2", "target": "cerca", "pl": "blisko"},
    {"id": "es_a2_010", "level": "A2", "target": "lejos", "pl": "daleko"},
    {"id": "es_a2_011", "level": "A2", "target": "encima", "pl": "na górze / nad"},
    {"id": "es_a2_012", "level": "A2", "target": "debajo", "pl": "pod"},
    {"id": "es_a2_013", "level": "A2", "target": "dentro", "pl": "wewnątrz"},
    {"id": "es_a2_014", "level": "A2", "target": "fuera", "pl": "na zewnątrz"},
    {"id": "es_a2_015", "level": "A2", "target": "al lado de", "pl": "obok"},
    {"id": "es_a2_016", "level": "A2", "target": "antes", "pl": "przed / wcześniej"},
    {"id": "es_a2_017", "level": "A2", "target": "después", "pl": "potem"},
    {"id": "es_a2_018", "level": "A2", "target": "durante", "pl": "podczas"},
    {"id": "es_a2_019", "level": "A2", "target": "entonces", "pl": "wtedy"},
    {"id": "es_a2_020", "level": "A2", "target": "también", "pl": "również"},
    {"id": "es_a2_021", "level": "A2", "target": "tampoco", "pl": "też nie"},
    {"id": "es_a2_022", "level": "A2", "target": "quizás", "pl": "być może"},
    {"id": "es_a2_023", "level": "A2", "target": "bastante", "pl": "dość"},
    {"id": "es_a2_024", "level": "A2", "target": "demasiado", "pl": "zbyt dużo"},
    {"id": "es_a2_025", "level": "A2", "target": "menos", "pl": "mniej"},
    {"id": "es_a2_026", "level": "A2", "target": "mejor", "pl": "lepiej"},
    {"id": "es_a2_027", "level": "A2", "target": "peor", "pl": "gorzej"},
    {"id": "es_a2_028", "level": "A2", "target": "fácil", "pl": "łatwy"},
    {"id": "es_a2_029", "level": "A2", "target": "difícil", "pl": "trudny"},
    {"id": "es_a2_030", "level": "A2", "target": "importante", "pl": "ważny"},
    {"id": "es_a2_031", "level": "A2", "target": "posible", "pl": "możliwy"},
    {"id": "es_a2_032", "level": "A2", "target": "diferente", "pl": "inny"},
    {"id": "es_a2_033", "level": "A2", "target": "igual", "pl": "taki sam"},
    {"id": "es_a2_034", "level": "A2", "target": "ocupado", "pl": "zajęty"},
    {"id": "es_a2_035", "level": "A2", "target": "libre", "pl": "wolny"},
    {"id": "es_a2_036", "level": "A2", "target": "cansado", "pl": "zmęczony"},
    {"id": "es_a2_037", "level": "A2", "target": "enfermo", "pl": "chory"},
    {"id": "es_a2_038", "level": "A2", "target": "contento", "pl": "zadowolony"},
    {"id": "es_a2_039", "level": "A2", "target": "preocupado", "pl": "zmartwiony"},
    {"id": "es_a2_040", "level": "A2", "target": "seguro", "pl": "bezpieczny / pewny"},
    {"id": "es_a2_041", "level": "A2", "target": "viaje", "pl": "podróż"},
    {"id": "es_a2_042", "level": "A2", "target": "billete", "pl": "bilet"},
    {"id": "es_a2_043", "level": "A2", "target": "estación", "pl": "stacja"},
    {"id": "es_a2_044", "level": "A2", "target": "aeropuerto", "pl": "lotnisko"},
    {"id": "es_a2_045", "level": "A2", "target": "hotel", "pl": "hotel"},
    {"id": "es_a2_046", "level": "A2", "target": "habitación", "pl": "pokój"},
    {"id": "es_a2_047", "level": "A2", "target": "reserva", "pl": "rezerwacja"},
    {"id": "es_a2_048", "level": "A2", "target": "maleta", "pl": "walizka"},
    {"id": "es_a2_049", "level": "A2", "target": "mapa", "pl": "mapa"},
    {"id": "es_a2_050", "level": "A2", "target": "dirección", "pl": "adres / kierunek"},
    {"id": "es_a2_051", "level": "A2", "target": "precio", "pl": "cena"},
    {"id": "es_a2_052", "level": "A2", "target": "dinero", "pl": "pieniądze"},
    {"id": "es_a2_053", "level": "A2", "target": "tarjeta", "pl": "karta"},
    {"id": "es_a2_054", "level": "A2", "target": "cuenta", "pl": "rachunek / konto"},
    {"id": "es_a2_055", "level": "A2", "target": "mercado", "pl": "rynek"},
    {"id": "es_a2_056", "level": "A2", "target": "restaurante", "pl": "restauracja"},
    {"id": "es_a2_057", "level": "A2", "target": "desayuno", "pl": "śniadanie"},
    {"id": "es_a2_058", "level": "A2", "target": "almuerzo", "pl": "lunch"},
    {"id": "es_a2_059", "level": "A2", "target": "cena", "pl": "kolacja"},
    {"id": "es_a2_060", "level": "A2", "target": "menú", "pl": "menu"},
    {"id": "es_a2_061", "level": "A2", "target": "pedir", "pl": "zamawiać / prosić"},
    {"id": "es_a2_062", "level": "A2", "target": "pagar", "pl": "płacić"},
    {"id": "es_a2_063", "level": "A2", "target": "costar", "pl": "kosztować"},
    {"id": "es_a2_064", "level": "A2", "target": "buscar", "pl": "szukać"},
    {"id": "es_a2_065", "level": "A2", "target": "encontrar", "pl": "znajdować"},
    {"id": "es_a2_066", "level": "A2", "target": "esperar", "pl": "czekać / mieć nadzieję"},
    {"id": "es_a2_067", "level": "A2", "target": "empezar", "pl": "zaczynać"},
    {"id": "es_a2_068", "level": "A2", "target": "terminar", "pl": "kończyć"},
    {"id": "es_a2_069", "level": "A2", "target": "volver", "pl": "wracać"},
    {"id": "es_a2_070", "level": "A2", "target": "llegar", "pl": "przybywać"},
    {"id": "es_a2_071", "level": "A2", "target": "salir", "pl": "wychodzić"},
    {"id": "es_a2_072", "level": "A2", "target": "entrar", "pl": "wchodzić"},
    {"id": "es_a2_073", "level": "A2", "target": "llevar", "pl": "nosić / zabierać"},
    {"id": "es_a2_074", "level": "A2", "target": "traer", "pl": "przynosić"},
    {"id": "es_a2_075", "level": "A2", "target": "usar", "pl": "używać"},
    {"id": "es_a2_076", "level": "A2", "target": "necesitar", "pl": "potrzebować"},
    {"id": "es_a2_077", "level": "A2", "target": "ayudar", "pl": "pomagać"},
    {"id": "es_a2_078", "level": "A2", "target": "preguntar", "pl": "pytać"},
    {"id": "es_a2_079", "level": "A2", "target": "responder", "pl": "odpowiadać"},
    {"id": "es_a2_080", "level": "A2", "target": "explicar", "pl": "wyjaśniać"},
    {"id": "es_a2_081", "level": "A2", "target": "entender", "pl": "rozumieć"},
    {"id": "es_a2_082", "level": "A2", "target": "aprender", "pl": "uczyć się"},
    {"id": "es_a2_083", "level": "A2", "target": "recordar", "pl": "pamiętać"},
    {"id": "es_a2_084", "level": "A2", "target": "olvidar", "pl": "zapominać"},
    {"id": "es_a2_085", "level": "A2", "target": "conocer", "pl": "znać / poznawać"},
    {"id": "es_a2_086", "level": "A2", "target": "¿cuánto cuesta?", "pl": "ile to kosztuje?"},
    {"id": "es_a2_087", "level": "A2", "target": "¿dónde está...?", "pl": "gdzie jest...?"},
    {"id": "es_a2_088", "level": "A2", "target": "me gustaría...", "pl": "chciałbym / chciałabym..."},
    {"id": "es_a2_089", "level": "A2", "target": "tengo que...", "pl": "muszę..."},
    {"id": "es_a2_090", "level": "A2", "target": "voy a...", "pl": "zamierzam..."},
    {"id": "es_b1_001", "level": "B1", "target": "aunque", "pl": "chociaż"},
    {"id": "es_b1_002", "level": "B1", "target": "sin embargo", "pl": "jednak"},
    {"id": "es_b1_003", "level": "B1", "target": "además", "pl": "ponadto"},
    {"id": "es_b1_004", "level": "B1", "target": "por eso", "pl": "dlatego"},
    {"id": "es_b1_005", "level": "B1", "target": "mientras", "pl": "podczas gdy"},
    {"id": "es_b1_006", "level": "B1", "target": "en cambio", "pl": "natomiast"},
    {"id": "es_b1_007", "level": "B1", "target": "por ejemplo", "pl": "na przykład"},
    {"id": "es_b1_008", "level": "B1", "target": "de hecho", "pl": "w rzeczywistości"},
    {"id": "es_b1_009", "level": "B1", "target": "al menos", "pl": "przynajmniej"},
    {"id": "es_b1_010", "level": "B1", "target": "en general", "pl": "ogólnie"},
    {"id": "es_b1_011", "level": "B1", "target": "acuerdo", "pl": "zgoda / porozumienie"},
    {"id": "es_b1_012", "level": "B1", "target": "opinión", "pl": "opinia"},
    {"id": "es_b1_013", "level": "B1", "target": "decisión", "pl": "decyzja"},
    {"id": "es_b1_014", "level": "B1", "target": "experiencia", "pl": "doświadczenie"},
    {"id": "es_b1_015", "level": "B1", "target": "oportunidad", "pl": "okazja / możliwość"},
    {"id": "es_b1_016", "level": "B1", "target": "problema", "pl": "problem"},
    {"id": "es_b1_017", "level": "B1", "target": "solución", "pl": "rozwiązanie"},
    {"id": "es_b1_018", "level": "B1", "target": "resultado", "pl": "wynik"},
    {"id": "es_b1_019", "level": "B1", "target": "razón", "pl": "powód"},
    {"id": "es_b1_020", "level": "B1", "target": "cambio", "pl": "zmiana"},
    {"id": "es_b1_021", "level": "B1", "target": "sociedad", "pl": "społeczeństwo"},
    {"id": "es_b1_022", "level": "B1", "target": "medio ambiente", "pl": "środowisko"},
    {"id": "es_b1_023", "level": "B1", "target": "salud", "pl": "zdrowie"},
    {"id": "es_b1_024", "level": "B1", "target": "educación", "pl": "edukacja"},
    {"id": "es_b1_025", "level": "B1", "target": "gobierno", "pl": "rząd"},
    {"id": "es_b1_026", "level": "B1", "target": "empresa", "pl": "firma"},
    {"id": "es_b1_027", "level": "B1", "target": "empleo", "pl": "zatrudnienie"},
    {"id": "es_b1_028", "level": "B1", "target": "sueldo", "pl": "pensja"},
    {"id": "es_b1_029", "level": "B1", "target": "reunión", "pl": "spotkanie"},
    {"id": "es_b1_030", "level": "B1", "target": "proyecto", "pl": "projekt"},
    {"id": "es_b1_031", "level": "B1", "target": "objetivo", "pl": "cel"},
    {"id": "es_b1_032", "level": "B1", "target": "riesgo", "pl": "ryzyko"},
    {"id": "es_b1_033", "level": "B1", "target": "ventaja", "pl": "zaleta"},
    {"id": "es_b1_034", "level": "B1", "target": "desventaja", "pl": "wada"},
    {"id": "es_b1_035", "level": "B1", "target": "éxito", "pl": "sukces"},
    {"id": "es_b1_036", "level": "B1", "target": "fracaso", "pl": "porażka"},
    {"id": "es_b1_037", "level": "B1", "target": "comportamiento", "pl": "zachowanie"},
    {"id": "es_b1_038", "level": "B1", "target": "relación", "pl": "relacja"},
    {"id": "es_b1_039", "level": "B1", "target": "confianza", "pl": "zaufanie"},
    {"id": "es_b1_040", "level": "B1", "target": "responsabilidad", "pl": "odpowiedzialność"},
    {"id": "es_b1_041", "level": "B1", "target": "mejorar", "pl": "poprawiać"},
    {"id": "es_b1_042", "level": "B1", "target": "aumentar", "pl": "zwiększać"},
    {"id": "es_b1_043", "level": "B1", "target": "reducir", "pl": "zmniejszać"},
    {"id": "es_b1_044", "level": "B1", "target": "evitar", "pl": "unikać"},
    {"id": "es_b1_045", "level": "B1", "target": "permitir", "pl": "pozwalać"},
    {"id": "es_b1_046", "level": "B1", "target": "prohibir", "pl": "zabraniać"},
    {"id": "es_b1_047", "level": "B1", "target": "conseguir", "pl": "osiągać / zdobywać"},
    {"id": "es_b1_048", "level": "B1", "target": "intentar", "pl": "próbować"},
    {"id": "es_b1_049", "level": "B1", "target": "lograr", "pl": "osiągać"},
    {"id": "es_b1_050", "level": "B1", "target": "decidir", "pl": "decydować"},
    {"id": "es_b1_051", "level": "B1", "target": "elegir", "pl": "wybierać"},
    {"id": "es_b1_052", "level": "B1", "target": "depender", "pl": "zależeć"},
    {"id": "es_b1_053", "level": "B1", "target": "parecer", "pl": "wydawać się"},
    {"id": "es_b1_054", "level": "B1", "target": "ocurrir", "pl": "wydarzać się"},
    {"id": "es_b1_055", "level": "B1", "target": "suceder", "pl": "zdarzać się"},
    {"id": "es_b1_056", "level": "B1", "target": "desarrollar", "pl": "rozwijać"},
    {"id": "es_b1_057", "level": "B1", "target": "crear", "pl": "tworzyć"},
    {"id": "es_b1_058", "level": "B1", "target": "compartir", "pl": "dzielić się"},
    {"id": "es_b1_059", "level": "B1", "target": "ofrecer", "pl": "oferować"},
    {"id": "es_b1_060", "level": "B1", "target": "aceptar", "pl": "akceptować"},
    {"id": "es_b1_061", "level": "B1", "target": "rechazar", "pl": "odrzucać"},
    {"id": "es_b1_062", "level": "B1", "target": "apoyar", "pl": "wspierać"},
    {"id": "es_b1_063", "level": "B1", "target": "proteger", "pl": "chronić"},
    {"id": "es_b1_064", "level": "B1", "target": "resolver", "pl": "rozwiązywać"},
    {"id": "es_b1_065", "level": "B1", "target": "comprobar", "pl": "sprawdzać"},
    {"id": "es_b1_066", "level": "B1", "target": "probablemente", "pl": "prawdopodobnie"},
    {"id": "es_b1_067", "level": "B1", "target": "especialmente", "pl": "szczególnie"},
    {"id": "es_b1_068", "level": "B1", "target": "realmente", "pl": "naprawdę"},
    {"id": "es_b1_069", "level": "B1", "target": "actualmente", "pl": "obecnie"},
    {"id": "es_b1_070", "level": "B1", "target": "finalmente", "pl": "ostatecznie"},
    {"id": "es_b1_071", "level": "B1", "target": "estar de acuerdo", "pl": "zgadzać się"},
    {"id": "es_b1_072", "level": "B1", "target": "darse cuenta", "pl": "zdać sobie sprawę"},
    {"id": "es_b1_073", "level": "B1", "target": "tener en cuenta", "pl": "brać pod uwagę"},
    {"id": "es_b1_074", "level": "B1", "target": "echar de menos", "pl": "tęsknić"},
    {"id": "es_b1_075", "level": "B1", "target": "llevarse bien", "pl": "dobrze się dogadywać"},
    {"id": "es_b1_076", "level": "B1", "target": "¿qué opinas de...?", "pl": "co sądzisz o...?"},
    {"id": "es_b1_077", "level": "B1", "target": "desde mi punto de vista", "pl": "z mojego punktu widzenia"},
    {"id": "es_b1_078", "level": "B1", "target": "depende de...", "pl": "to zależy od..."},
    {"id": "es_b1_079", "level": "B1", "target": "no estoy seguro de que...", "pl": "nie jestem pewien, czy..."},
    {"id": "es_b1_080", "level": "B1", "target": "lo importante es que...", "pl": "ważne jest to, że..."},
    {"id": "es_b2_001", "level": "B2", "target": "a pesar de", "pl": "pomimo"},
    {"id": "es_b2_002", "level": "B2", "target": "por lo tanto", "pl": "w związku z tym"},
    {"id": "es_b2_003", "level": "B2", "target": "no obstante", "pl": "niemniej jednak"},
    {"id": "es_b2_004", "level": "B2", "target": "por consiguiente", "pl": "w konsekwencji"},
    {"id": "es_b2_005", "level": "B2", "target": "en cuanto a", "pl": "jeśli chodzi o"},
    {"id": "es_b2_006", "level": "B2", "target": "con respecto a", "pl": "w odniesieniu do"},
    {"id": "es_b2_007", "level": "B2", "target": "a medida que", "pl": "w miarę jak"},
    {"id": "es_b2_008", "level": "B2", "target": "siempre que", "pl": "pod warunkiem że"},
    {"id": "es_b2_009", "level": "B2", "target": "a menos que", "pl": "chyba że"},
    {"id": "es_b2_010", "level": "B2", "target": "puesto que", "pl": "ponieważ"},
    {"id": "es_b2_011", "level": "B2", "target": "planteamiento", "pl": "podejście / ujęcie"},
    {"id": "es_b2_012", "level": "B2", "target": "perspectiva", "pl": "perspektywa"},
    {"id": "es_b2_013", "level": "B2", "target": "consecuencia", "pl": "konsekwencja"},
    {"id": "es_b2_014", "level": "B2", "target": "circunstancia", "pl": "okoliczność"},
    {"id": "es_b2_015", "level": "B2", "target": "tendencia", "pl": "tendencja"},
    {"id": "es_b2_016", "level": "B2", "target": "desafío", "pl": "wyzwanie"},
    {"id": "es_b2_017", "level": "B2", "target": "alcance", "pl": "zakres / zasięg"},
    {"id": "es_b2_018", "level": "B2", "target": "evidencia", "pl": "dowód / dane"},
    {"id": "es_b2_019", "level": "B2", "target": "entorno", "pl": "otoczenie"},
    {"id": "es_b2_020", "level": "B2", "target": "recurso", "pl": "zasób"},
    {"id": "es_b2_021", "level": "B2", "target": "rendimiento", "pl": "wydajność / wynik"},
    {"id": "es_b2_022", "level": "B2", "target": "crecimiento", "pl": "wzrost"},
    {"id": "es_b2_023", "level": "B2", "target": "reducción", "pl": "redukcja"},
    {"id": "es_b2_024", "level": "B2", "target": "impacto", "pl": "wpływ"},
    {"id": "es_b2_025", "level": "B2", "target": "enfoque", "pl": "podejście"},
    {"id": "es_b2_026", "level": "B2", "target": "criterio", "pl": "kryterium"},
    {"id": "es_b2_027", "level": "B2", "target": "supuesto", "pl": "założenie"},
    {"id": "es_b2_028", "level": "B2", "target": "prioridad", "pl": "priorytet"},
    {"id": "es_b2_029", "level": "B2", "target": "compromiso", "pl": "zobowiązanie / kompromis"},
    {"id": "es_b2_030", "level": "B2", "target": "conciencia", "pl": "świadomość"},
    {"id": "es_b2_031", "level": "B2", "target": "destacar", "pl": "wyróżniać / podkreślać"},
    {"id": "es_b2_032", "level": "B2", "target": "señalar", "pl": "wskazywać"},
    {"id": "es_b2_033", "level": "B2", "target": "demostrar", "pl": "wykazywać"},
    {"id": "es_b2_034", "level": "B2", "target": "suponer", "pl": "zakładać"},
    {"id": "es_b2_035", "level": "B2", "target": "implicar", "pl": "wiązać się / oznaczać"},
    {"id": "es_b2_036", "level": "B2", "target": "abarcar", "pl": "obejmować"},
    {"id": "es_b2_037", "level": "B2", "target": "afrontar", "pl": "stawiać czoła"},
    {"id": "es_b2_038", "level": "B2", "target": "fomentar", "pl": "wspierać / promować"},
    {"id": "es_b2_039", "level": "B2", "target": "garantizar", "pl": "gwarantować"},
    {"id": "es_b2_040", "level": "B2", "target": "mantener", "pl": "utrzymywać"},
    {"id": "es_b2_041", "level": "B2", "target": "alcanzar", "pl": "osiągać"},
    {"id": "es_b2_042", "level": "B2", "target": "establecer", "pl": "ustanawiać"},
    {"id": "es_b2_043", "level": "B2", "target": "determinar", "pl": "określać"},
    {"id": "es_b2_044", "level": "B2", "target": "considerar", "pl": "rozważać"},
    {"id": "es_b2_045", "level": "B2", "target": "cuestionar", "pl": "kwestionować"},
    {"id": "es_b2_046", "level": "B2", "target": "argumentar", "pl": "argumentować"},
    {"id": "es_b2_047", "level": "B2", "target": "justificar", "pl": "uzasadniać"},
    {"id": "es_b2_048", "level": "B2", "target": "evaluar", "pl": "oceniać"},
    {"id": "es_b2_049", "level": "B2", "target": "prever", "pl": "przewidywać"},
    {"id": "es_b2_050", "level": "B2", "target": "asumir", "pl": "przyjmować / zakładać"},
    {"id": "es_b2_051", "level": "B2", "target": "surgir", "pl": "pojawiać się"},
    {"id": "es_b2_052", "level": "B2", "target": "carecer de", "pl": "nie mieć / brakować"},
    {"id": "es_b2_053", "level": "B2", "target": "contribuir", "pl": "przyczyniać się"},
    {"id": "es_b2_054", "level": "B2", "target": "desempeñar", "pl": "pełnić / wykonywać"},
    {"id": "es_b2_055", "level": "B2", "target": "gestionar", "pl": "zarządzać"},
    {"id": "es_b2_056", "level": "B2", "target": "sostenible", "pl": "zrównoważony"},
    {"id": "es_b2_057", "level": "B2", "target": "adecuado", "pl": "odpowiedni"},
    {"id": "es_b2_058", "level": "B2", "target": "significativo", "pl": "znaczący"},
    {"id": "es_b2_059", "level": "B2", "target": "fundamental", "pl": "fundamentalny"},
    {"id": "es_b2_060", "level": "B2", "target": "complejo", "pl": "złożony"},
    {"id": "es_b2_061", "level": "B2", "target": "amplio", "pl": "szeroki"},
    {"id": "es_b2_062", "level": "B2", "target": "limitado", "pl": "ograniczony"},
    {"id": "es_b2_063", "level": "B2", "target": "eficaz", "pl": "skuteczny"},
    {"id": "es_b2_064", "level": "B2", "target": "probable", "pl": "prawdopodobny"},
    {"id": "es_b2_065", "level": "B2", "target": "relevante", "pl": "istotny"},
    {"id": "es_b2_066", "level": "B2", "target": "en gran medida", "pl": "w dużej mierze"},
    {"id": "es_b2_067", "level": "B2", "target": "hasta cierto punto", "pl": "do pewnego stopnia"},
    {"id": "es_b2_068", "level": "B2", "target": "a largo plazo", "pl": "w długim okresie"},
    {"id": "es_b2_069", "level": "B2", "target": "en última instancia", "pl": "ostatecznie"},
    {"id": "es_b2_070", "level": "B2", "target": "por una parte", "pl": "z jednej strony"},
    {"id": "es_b2_071", "level": "B2", "target": "por otra parte", "pl": "z drugiej strony"},
    {"id": "es_b2_072", "level": "B2", "target": "cabe destacar que", "pl": "warto podkreślić, że"},
    {"id": "es_b2_073", "level": "B2", "target": "conviene tener en cuenta", "pl": "warto wziąć pod uwagę"},
    {"id": "es_b2_074", "level": "B2", "target": "se trata de", "pl": "chodzi o"},
    {"id": "es_b2_075", "level": "B2", "target": "dar lugar a", "pl": "prowadzić do"},
    {"id": "es_b2_076", "level": "B2", "target": "llevar a cabo", "pl": "przeprowadzać"},
    {"id": "es_b2_077", "level": "B2", "target": "poner de manifiesto", "pl": "uwidaczniać"},
    {"id": "es_b2_078", "level": "B2", "target": "hacer frente a", "pl": "stawiać czoła"},
    {"id": "es_b2_079", "level": "B2", "target": "tener lugar", "pl": "mieć miejsce"},
    {"id": "es_b2_080", "level": "B2", "target": "estar dispuesto a", "pl": "być gotowym do"}
  ],
  english: [
    {"id": "en_a1_001", "level": "A1", "target": "hello", "pl": "cześć"},
    {"id": "en_a1_002", "level": "A1", "target": "goodbye", "pl": "do widzenia"},
    {"id": "en_a1_003", "level": "A1", "target": "please", "pl": "proszę"},
    {"id": "en_a1_004", "level": "A1", "target": "thank you", "pl": "dziękuję"},
    {"id": "en_a1_005", "level": "A1", "target": "yes", "pl": "tak"},
    {"id": "en_a1_006", "level": "A1", "target": "no", "pl": "nie"},
    {"id": "en_a1_007", "level": "A1", "target": "morning", "pl": "rano"},
    {"id": "en_a1_008", "level": "A1", "target": "evening", "pl": "wieczór"},
    {"id": "en_a1_009", "level": "A1", "target": "today", "pl": "dzisiaj"},
    {"id": "en_a1_010", "level": "A1", "target": "tomorrow", "pl": "jutro"},
    {"id": "en_a1_011", "level": "A1", "target": "yesterday", "pl": "wczoraj"},
    {"id": "en_a1_012", "level": "A1", "target": "now", "pl": "teraz"},
    {"id": "en_a1_013", "level": "A1", "target": "house", "pl": "dom"},
    {"id": "en_a1_014", "level": "A1", "target": "car", "pl": "samochód"},
    {"id": "en_a1_015", "level": "A1", "target": "work", "pl": "praca"},
    {"id": "en_a1_016", "level": "A1", "target": "family", "pl": "rodzina"},
    {"id": "en_a1_017", "level": "A1", "target": "friend", "pl": "przyjaciel"},
    {"id": "en_a1_018", "level": "A1", "target": "water", "pl": "woda"},
    {"id": "en_a1_019", "level": "A1", "target": "food", "pl": "jedzenie"},
    {"id": "en_a1_020", "level": "A1", "target": "shop", "pl": "sklep"},
    {"id": "en_a1_021", "level": "A1", "target": "school", "pl": "szkoła"},
    {"id": "en_a1_022", "level": "A1", "target": "road", "pl": "droga"},
    {"id": "en_a1_023", "level": "A1", "target": "city", "pl": "miasto"},
    {"id": "en_a1_024", "level": "A1", "target": "money", "pl": "pieniądze"},
    {"id": "en_a1_025", "level": "A1", "target": "time", "pl": "czas"},
    {"id": "en_a1_026", "level": "A1", "target": "day", "pl": "dzień"},
    {"id": "en_a1_027", "level": "A1", "target": "week", "pl": "tydzień"},
    {"id": "en_a1_028", "level": "A1", "target": "big", "pl": "duży"},
    {"id": "en_a1_029", "level": "A1", "target": "small", "pl": "mały"},
    {"id": "en_a1_030", "level": "A1", "target": "good", "pl": "dobry"},
    {"id": "en_a1_031", "level": "A1", "target": "bad", "pl": "zły"},
    {"id": "en_a1_032", "level": "A1", "target": "new", "pl": "nowy"},
    {"id": "en_a1_033", "level": "A1", "target": "old", "pl": "stary"},
    {"id": "en_a1_034", "level": "A1", "target": "fast", "pl": "szybki"},
    {"id": "en_a1_035", "level": "A1", "target": "slow", "pl": "wolny"},
    {"id": "en_a1_036", "level": "A1", "target": "eat", "pl": "jeść"},
    {"id": "en_a1_037", "level": "A1", "target": "drink", "pl": "pić"},
    {"id": "en_a1_038", "level": "A1", "target": "go", "pl": "iść / jechać"},
    {"id": "en_a1_039", "level": "A1", "target": "come", "pl": "przychodzić"},
    {"id": "en_a1_040", "level": "A1", "target": "speak", "pl": "mówić"},
    {"id": "en_a1_041", "level": "A1", "target": "listen", "pl": "słuchać"},
    {"id": "en_a1_042", "level": "A1", "target": "read", "pl": "czytać"},
    {"id": "en_a1_043", "level": "A1", "target": "write", "pl": "pisać"},
    {"id": "en_a1_044", "level": "A1", "target": "want", "pl": "chcieć"},
    {"id": "en_a1_045", "level": "A1", "target": "need", "pl": "potrzebować"},
    {"id": "en_a1_046", "level": "A1", "target": "have", "pl": "mieć"},
    {"id": "en_a1_047", "level": "A1", "target": "make", "pl": "robić / tworzyć"},
    {"id": "en_a1_048", "level": "A1", "target": "buy", "pl": "kupować"},
    {"id": "en_a1_049", "level": "A1", "target": "pay", "pl": "płacić"},
    {"id": "en_a1_050", "level": "A1", "target": "open", "pl": "otwierać"},
    {"id": "en_a1_051", "level": "A1", "target": "close", "pl": "zamykać"},
    {"id": "en_a2_052", "level": "A2", "target": "arrive", "pl": "przyjeżdżać / przybywać"},
    {"id": "en_a2_053", "level": "A2", "target": "leave", "pl": "wyjeżdżać / opuszczać"},
    {"id": "en_a2_054", "level": "A2", "target": "borrow", "pl": "pożyczać od kogoś"},
    {"id": "en_a2_055", "level": "A2", "target": "lend", "pl": "pożyczać komuś"},
    {"id": "en_a2_056", "level": "A2", "target": "choose", "pl": "wybierać"},
    {"id": "en_a2_057", "level": "A2", "target": "decide", "pl": "decydować"},
    {"id": "en_a2_058", "level": "A2", "target": "explain", "pl": "wyjaśniać"},
    {"id": "en_a2_059", "level": "A2", "target": "forget", "pl": "zapominać"},
    {"id": "en_a2_060", "level": "A2", "target": "remember", "pl": "pamiętać"},
    {"id": "en_a2_061", "level": "A2", "target": "invite", "pl": "zapraszać"},
    {"id": "en_a2_062", "level": "A2", "target": "meet", "pl": "spotykać"},
    {"id": "en_a2_063", "level": "A2", "target": "move", "pl": "przeprowadzać się / poruszać"},
    {"id": "en_a2_064", "level": "A2", "target": "order", "pl": "zamawiać"},
    {"id": "en_a2_065", "level": "A2", "target": "plan", "pl": "planować"},
    {"id": "en_a2_066", "level": "A2", "target": "repair", "pl": "naprawiać"},
    {"id": "en_a2_067", "level": "A2", "target": "return", "pl": "wracać / zwracać"},
    {"id": "en_a2_068", "level": "A2", "target": "send", "pl": "wysyłać"},
    {"id": "en_a2_069", "level": "A2", "target": "spend", "pl": "wydawać / spędzać"},
    {"id": "en_a2_070", "level": "A2", "target": "stay", "pl": "zostawać"},
    {"id": "en_a2_071", "level": "A2", "target": "travel", "pl": "podróżować"},
    {"id": "en_a2_072", "level": "A2", "target": "wait", "pl": "czekać"},
    {"id": "en_a2_073", "level": "A2", "target": "wear", "pl": "nosić"},
    {"id": "en_a2_074", "level": "A2", "target": "weather", "pl": "pogoda"},
    {"id": "en_a2_075", "level": "A2", "target": "journey", "pl": "podróż"},
    {"id": "en_a2_076", "level": "A2", "target": "appointment", "pl": "spotkanie / wizyta"},
    {"id": "en_a2_077", "level": "A2", "target": "neighbour", "pl": "sąsiad"},
    {"id": "en_a2_078", "level": "A2", "target": "quiet", "pl": "cichy"},
    {"id": "en_a2_079", "level": "A2", "target": "busy", "pl": "zajęty"},
    {"id": "en_a2_080", "level": "A2", "target": "early", "pl": "wcześnie"},
    {"id": "en_a2_081", "level": "A2", "target": "late", "pl": "późno"},
    {"id": "en_a2_082", "level": "A2", "target": "enough", "pl": "wystarczająco"},
    {"id": "en_a2_083", "level": "A2", "target": "usually", "pl": "zwykle"},
    {"id": "en_a2_084", "level": "A2", "target": "sometimes", "pl": "czasami"},
    {"id": "en_a2_085", "level": "A2", "target": "already", "pl": "już"},
    {"id": "en_a2_086", "level": "A2", "target": "still", "pl": "nadal"},
    {"id": "en_a2_087", "level": "A2", "target": "almost", "pl": "prawie"},
    {"id": "en_a2_088", "level": "A2", "target": "perhaps", "pl": "być może"},
    {"id": "en_a2_089", "level": "A2", "target": "because", "pl": "ponieważ"},
    {"id": "en_a2_090", "level": "A2", "target": "although", "pl": "chociaż"},
    {"id": "en_a2_091", "level": "A2", "target": "during", "pl": "podczas"},
    {"id": "en_a2_092", "level": "A2", "target": "without", "pl": "bez"},
    {"id": "en_a2_093", "level": "A2", "target": "instead", "pl": "zamiast"},
    {"id": "en_b1_094", "level": "B1", "target": "achieve", "pl": "osiągać"},
    {"id": "en_b1_095", "level": "B1", "target": "admit", "pl": "przyznawać"},
    {"id": "en_b1_096", "level": "B1", "target": "avoid", "pl": "unikać"},
    {"id": "en_b1_097", "level": "B1", "target": "behave", "pl": "zachowywać się"},
    {"id": "en_b1_098", "level": "B1", "target": "compare", "pl": "porównywać"},
    {"id": "en_b1_099", "level": "B1", "target": "complain", "pl": "skarżyć się"},
    {"id": "en_b1_100", "level": "B1", "target": "consider", "pl": "rozważać"},
    {"id": "en_b1_101", "level": "B1", "target": "depend", "pl": "zależeć"},
    {"id": "en_b1_102", "level": "B1", "target": "develop", "pl": "rozwijać"},
    {"id": "en_b1_103", "level": "B1", "target": "expect", "pl": "oczekiwać"},
    {"id": "en_b1_104", "level": "B1", "target": "improve", "pl": "poprawiać / ulepszać"},
    {"id": "en_b1_105", "level": "B1", "target": "increase", "pl": "zwiększać"},
    {"id": "en_b1_106", "level": "B1", "target": "manage", "pl": "dawać sobie radę / zarządzać"},
    {"id": "en_b1_107", "level": "B1", "target": "notice", "pl": "zauważać"},
    {"id": "en_b1_108", "level": "B1", "target": "offer", "pl": "oferować"},
    {"id": "en_b1_109", "level": "B1", "target": "provide", "pl": "zapewniać"},
    {"id": "en_b1_110", "level": "B1", "target": "realise", "pl": "uświadamiać sobie"},
    {"id": "en_b1_111", "level": "B1", "target": "recommend", "pl": "polecać"},
    {"id": "en_b1_112", "level": "B1", "target": "reduce", "pl": "zmniejszać"},
    {"id": "en_b1_113", "level": "B1", "target": "refuse", "pl": "odmawiać"},
    {"id": "en_b1_114", "level": "B1", "target": "require", "pl": "wymagać"},
    {"id": "en_b1_115", "level": "B1", "target": "seem", "pl": "wydawać się"},
    {"id": "en_b1_116", "level": "B1", "target": "suggest", "pl": "sugerować"},
    {"id": "en_b1_117", "level": "B1", "target": "support", "pl": "wspierać"},
    {"id": "en_b1_118", "level": "B1", "target": "experience", "pl": "doświadczenie"},
    {"id": "en_b1_119", "level": "B1", "target": "advantage", "pl": "zaleta"},
    {"id": "en_b1_120", "level": "B1", "target": "disadvantage", "pl": "wada"},
    {"id": "en_b1_121", "level": "B1", "target": "decision", "pl": "decyzja"},
    {"id": "en_b1_122", "level": "B1", "target": "environment", "pl": "środowisko"},
    {"id": "en_b1_123", "level": "B1", "target": "opportunity", "pl": "okazja / możliwość"},
    {"id": "en_b1_124", "level": "B1", "target": "relationship", "pl": "relacja"},
    {"id": "en_b1_125", "level": "B1", "target": "responsibility", "pl": "odpowiedzialność"},
    {"id": "en_b1_126", "level": "B1", "target": "solution", "pl": "rozwiązanie"},
    {"id": "en_b1_127", "level": "B1", "target": "successful", "pl": "udany / odnoszący sukces"},
    {"id": "en_b1_128", "level": "B1", "target": "likely", "pl": "prawdopodobny"},
    {"id": "en_b1_129", "level": "B1", "target": "available", "pl": "dostępny"},
    {"id": "en_b1_130", "level": "B1", "target": "necessary", "pl": "konieczny"},
    {"id": "en_b1_131", "level": "B1", "target": "recent", "pl": "niedawny"},
    {"id": "en_b1_132", "level": "B1", "target": "instead of", "pl": "zamiast"},
    {"id": "en_b1_133", "level": "B1", "target": "as soon as", "pl": "jak tylko"},
    {"id": "en_b2_134", "level": "B2", "target": "acknowledge", "pl": "uznawać / przyznawać"},
    {"id": "en_b2_135", "level": "B2", "target": "assume", "pl": "zakładać"},
    {"id": "en_b2_136", "level": "B2", "target": "convince", "pl": "przekonywać"},
    {"id": "en_b2_137", "level": "B2", "target": "decline", "pl": "odmawiać / spadać"},
    {"id": "en_b2_138", "level": "B2", "target": "demonstrate", "pl": "wykazywać / demonstrować"},
    {"id": "en_b2_139", "level": "B2", "target": "emphasise", "pl": "podkreślać"},
    {"id": "en_b2_140", "level": "B2", "target": "encounter", "pl": "napotykać"},
    {"id": "en_b2_141", "level": "B2", "target": "ensure", "pl": "zapewniać"},
    {"id": "en_b2_142", "level": "B2", "target": "establish", "pl": "ustanawiać / ustalać"},
    {"id": "en_b2_143", "level": "B2", "target": "evaluate", "pl": "oceniać"},
    {"id": "en_b2_144", "level": "B2", "target": "maintain", "pl": "utrzymywać"},
    {"id": "en_b2_145", "level": "B2", "target": "negotiate", "pl": "negocjować"},
    {"id": "en_b2_146", "level": "B2", "target": "overcome", "pl": "przezwyciężać"},
    {"id": "en_b2_147", "level": "B2", "target": "persuade", "pl": "przekonywać"},
    {"id": "en_b2_148", "level": "B2", "target": "prevent", "pl": "zapobiegać"},
    {"id": "en_b2_149", "level": "B2", "target": "recognise", "pl": "rozpoznawać / uznawać"},
    {"id": "en_b2_150", "level": "B2", "target": "regardless", "pl": "niezależnie"},
    {"id": "en_b2_151", "level": "B2", "target": "reliable", "pl": "niezawodny / wiarygodny"},
    {"id": "en_b2_152", "level": "B2", "target": "significant", "pl": "znaczący"},
    {"id": "en_b2_153", "level": "B2", "target": "sufficient", "pl": "wystarczający"},
    {"id": "en_b2_154", "level": "B2", "target": "therefore", "pl": "dlatego / zatem"},
    {"id": "en_b2_155", "level": "B2", "target": "whereas", "pl": "podczas gdy"},
    {"id": "en_b2_156", "level": "B2", "target": "nevertheless", "pl": "niemniej jednak"},
    {"id": "en_b2_157", "level": "B2", "target": "consequently", "pl": "w konsekwencji"},
    {"id": "en_b2_158", "level": "B2", "target": "approach", "pl": "podejście"},
    {"id": "en_b2_159", "level": "B2", "target": "awareness", "pl": "świadomość"},
    {"id": "en_b2_160", "level": "B2", "target": "circumstance", "pl": "okoliczność"},
    {"id": "en_b2_161", "level": "B2", "target": "commitment", "pl": "zaangażowanie"},
    {"id": "en_b2_162", "level": "B2", "target": "consequence", "pl": "konsekwencja"},
    {"id": "en_b2_163", "level": "B2", "target": "evidence", "pl": "dowód / materiał dowodowy"},
    {"id": "en_b2_164", "level": "B2", "target": "impact", "pl": "wpływ"},
    {"id": "en_b2_165", "level": "B2", "target": "issue", "pl": "kwestia / problem"},
    {"id": "en_b2_166", "level": "B2", "target": "outcome", "pl": "wynik / rezultat"},
    {"id": "en_b2_167", "level": "B2", "target": "perspective", "pl": "perspektywa"},
    {"id": "en_b2_168", "level": "B2", "target": "requirement", "pl": "wymóg"},
    {"id": "en_b2_169", "level": "B2", "target": "shortage", "pl": "niedobór"},
    {"id": "en_b2_170", "level": "B2", "target": "tendency", "pl": "tendencja"},
    {"id": "en_b2_171", "level": "B2", "target": "workload", "pl": "obciążenie pracą"}
  ]
};
