/* LinguaCore v0.8.0 — course data */
const COURSE_DATA = {
  spanish: [
    {"id": "es_a1_001", "level": "A1", "target": "hola", "pl": "cześć"},
    {"id": "es_a1_002", "level": "A1", "target": "adiós", "pl": "do widzenia"},
    {"id": "es_a1_003", "level": "A1", "target": "gracias", "pl": "dziękuję"},
    {"id": "es_a1_004", "level": "A1", "target": "por favor", "pl": "proszę"},
    {"id": "es_a1_005", "level": "A1", "target": "sí", "pl": "tak"},
    {"id": "es_a1_006", "level": "A1", "target": "no", "pl": "nie"},
    {"id": "es_a1_007", "level": "A1", "target": "buenos días", "pl": "dzień dobry"},
    {"id": "es_a1_008", "level": "A1", "target": "buenas noches", "pl": "dobranoc"},
    {"id": "es_a1_009", "level": "A1", "target": "¿cómo estás?", "pl": "jak się masz?"},
    {"id": "es_a1_010", "level": "A1", "target": "bien", "pl": "dobrze"},
    {"id": "es_a1_011", "level": "A1", "target": "mal", "pl": "źle"},
    {"id": "es_a1_012", "level": "A1", "target": "agua", "pl": "woda"},
    {"id": "es_a1_013", "level": "A1", "target": "comida", "pl": "jedzenie"},
    {"id": "es_a1_014", "level": "A1", "target": "casa", "pl": "dom"},
    {"id": "es_a1_015", "level": "A1", "target": "coche", "pl": "samochód"},
    {"id": "es_a1_016", "level": "A1", "target": "trabajo", "pl": "praca"},
    {"id": "es_a1_017", "level": "A1", "target": "familia", "pl": "rodzina"},
    {"id": "es_a1_018", "level": "A1", "target": "amigo", "pl": "przyjaciel"},
    {"id": "es_a1_019", "level": "A1", "target": "mujer", "pl": "kobieta"},
    {"id": "es_a1_020", "level": "A1", "target": "hombre", "pl": "mężczyzna"},
    {"id": "es_a1_021", "level": "A1", "target": "niño", "pl": "chłopiec"},
    {"id": "es_a1_022", "level": "A1", "target": "niña", "pl": "dziewczynka"},
    {"id": "es_a1_023", "level": "A1", "target": "día", "pl": "dzień"},
    {"id": "es_a1_024", "level": "A1", "target": "noche", "pl": "noc"},
    {"id": "es_a1_025", "level": "A1", "target": "hoy", "pl": "dzisiaj"},
    {"id": "es_a1_026", "level": "A1", "target": "mañana", "pl": "jutro"},
    {"id": "es_a1_027", "level": "A1", "target": "ayer", "pl": "wczoraj"},
    {"id": "es_a1_028", "level": "A1", "target": "ahora", "pl": "teraz"},
    {"id": "es_a1_029", "level": "A1", "target": "aquí", "pl": "tutaj"},
    {"id": "es_a1_030", "level": "A1", "target": "allí", "pl": "tam"},
    {"id": "es_a1_031", "level": "A1", "target": "grande", "pl": "duży"},
    {"id": "es_a1_032", "level": "A1", "target": "pequeño", "pl": "mały"},
    {"id": "es_a1_033", "level": "A1", "target": "bueno", "pl": "dobry"},
    {"id": "es_a1_034", "level": "A1", "target": "nuevo", "pl": "nowy"},
    {"id": "es_a1_035", "level": "A1", "target": "viejo", "pl": "stary"},
    {"id": "es_a1_036", "level": "A1", "target": "rápido", "pl": "szybki"},
    {"id": "es_a1_037", "level": "A1", "target": "lento", "pl": "wolny"},
    {"id": "es_a1_038", "level": "A1", "target": "comer", "pl": "jeść"},
    {"id": "es_a1_039", "level": "A1", "target": "beber", "pl": "pić"},
    {"id": "es_a1_040", "level": "A1", "target": "ir", "pl": "iść / jechać"},
    {"id": "es_a1_041", "level": "A1", "target": "venir", "pl": "przychodzić / przyjeżdżać"},
    {"id": "es_a1_042", "level": "A1", "target": "hablar", "pl": "mówić"},
    {"id": "es_a1_043", "level": "A1", "target": "escuchar", "pl": "słuchać"},
    {"id": "es_a1_044", "level": "A1", "target": "ver", "pl": "widzieć"},
    {"id": "es_a1_045", "level": "A1", "target": "leer", "pl": "czytać"},
    {"id": "es_a1_046", "level": "A1", "target": "escribir", "pl": "pisać"},
    {"id": "es_a1_047", "level": "A1", "target": "querer", "pl": "chcieć"},
    {"id": "es_a1_048", "level": "A1", "target": "tener", "pl": "mieć"},
    {"id": "es_a1_049", "level": "A1", "target": "hacer", "pl": "robić"},
    {"id": "es_a1_050", "level": "A1", "target": "comprar", "pl": "kupować"},
    {"id": "es_a1_051", "level": "A1", "target": "uno", "pl": "jeden"},
    {"id": "es_a1_052", "level": "A1", "target": "dos", "pl": "dwa"},
    {"id": "es_a1_053", "level": "A1", "target": "tres", "pl": "trzy"},
    {"id": "es_a1_054", "level": "A1", "target": "cuatro", "pl": "cztery"},
    {"id": "es_a1_055", "level": "A1", "target": "cinco", "pl": "pięć"},
    {"id": "es_a1_056", "level": "A1", "target": "calle", "pl": "ulica"},
    {"id": "es_a1_057", "level": "A1", "target": "tienda", "pl": "sklep"},
    {"id": "es_a1_058", "level": "A1", "target": "escuela", "pl": "szkoła"},
    {"id": "es_a1_059", "level": "A1", "target": "hotel", "pl": "hotel"},
    {"id": "es_a1_060", "level": "A1", "target": "aeropuerto", "pl": "lotnisko"}
  ],
  english: [
    {"id": "en_a1_001", "level": "A1", "target": "hello", "pl": "cześć"},
    {"id": "en_a1_002", "level": "A1", "target": "goodbye", "pl": "do widzenia"},
    {"id": "en_a1_003", "level": "A1", "target": "please", "pl": "proszę"},
    {"id": "en_a1_004", "level": "A1", "target": "thank you", "pl": "dziękuję"},
    {"id": "en_a1_005", "level": "A1", "target": "yes", "pl": "tak"},
    {"id": "en_a1_006", "level": "A1", "target": "no", "pl": "nie"},
    {"id": "en_a1_007", "level": "A1", "target": "morning", "pl": "rano"},
    {"id": "en_a1_008", "level": "A1", "target": "evening", "pl": "wieczór"},
    {"id": "en_a1_009", "level": "A1", "target": "today", "pl": "dzisiaj"},
    {"id": "en_a1_010", "level": "A1", "target": "tomorrow", "pl": "jutro"},
    {"id": "en_a1_011", "level": "A1", "target": "yesterday", "pl": "wczoraj"},
    {"id": "en_a1_012", "level": "A1", "target": "now", "pl": "teraz"},
    {"id": "en_a1_013", "level": "A1", "target": "house", "pl": "dom"},
    {"id": "en_a1_014", "level": "A1", "target": "car", "pl": "samochód"},
    {"id": "en_a1_015", "level": "A1", "target": "work", "pl": "praca"},
    {"id": "en_a1_016", "level": "A1", "target": "family", "pl": "rodzina"},
    {"id": "en_a1_017", "level": "A1", "target": "friend", "pl": "przyjaciel"},
    {"id": "en_a1_018", "level": "A1", "target": "water", "pl": "woda"},
    {"id": "en_a1_019", "level": "A1", "target": "food", "pl": "jedzenie"},
    {"id": "en_a1_020", "level": "A1", "target": "shop", "pl": "sklep"},
    {"id": "en_a1_021", "level": "A1", "target": "school", "pl": "szkoła"},
    {"id": "en_a1_022", "level": "A1", "target": "road", "pl": "droga"},
    {"id": "en_a1_023", "level": "A1", "target": "city", "pl": "miasto"},
    {"id": "en_a1_024", "level": "A1", "target": "money", "pl": "pieniądze"},
    {"id": "en_a1_025", "level": "A1", "target": "time", "pl": "czas"},
    {"id": "en_a1_026", "level": "A1", "target": "day", "pl": "dzień"},
    {"id": "en_a1_027", "level": "A1", "target": "week", "pl": "tydzień"},
    {"id": "en_a1_028", "level": "A1", "target": "big", "pl": "duży"},
    {"id": "en_a1_029", "level": "A1", "target": "small", "pl": "mały"},
    {"id": "en_a1_030", "level": "A1", "target": "good", "pl": "dobry"},
    {"id": "en_a1_031", "level": "A1", "target": "bad", "pl": "zły"},
    {"id": "en_a1_032", "level": "A1", "target": "new", "pl": "nowy"},
    {"id": "en_a1_033", "level": "A1", "target": "old", "pl": "stary"},
    {"id": "en_a1_034", "level": "A1", "target": "fast", "pl": "szybki"},
    {"id": "en_a1_035", "level": "A1", "target": "slow", "pl": "wolny"},
    {"id": "en_a1_036", "level": "A1", "target": "eat", "pl": "jeść"},
    {"id": "en_a1_037", "level": "A1", "target": "drink", "pl": "pić"},
    {"id": "en_a1_038", "level": "A1", "target": "go", "pl": "iść / jechać"},
    {"id": "en_a1_039", "level": "A1", "target": "come", "pl": "przychodzić"},
    {"id": "en_a1_040", "level": "A1", "target": "speak", "pl": "mówić"},
    {"id": "en_a1_041", "level": "A1", "target": "listen", "pl": "słuchać"},
    {"id": "en_a1_042", "level": "A1", "target": "read", "pl": "czytać"},
    {"id": "en_a1_043", "level": "A1", "target": "write", "pl": "pisać"},
    {"id": "en_a1_044", "level": "A1", "target": "want", "pl": "chcieć"},
    {"id": "en_a1_045", "level": "A1", "target": "need", "pl": "potrzebować"},
    {"id": "en_a1_046", "level": "A1", "target": "have", "pl": "mieć"},
    {"id": "en_a1_047", "level": "A1", "target": "make", "pl": "robić / tworzyć"},
    {"id": "en_a1_048", "level": "A1", "target": "buy", "pl": "kupować"},
    {"id": "en_a1_049", "level": "A1", "target": "pay", "pl": "płacić"},
    {"id": "en_a1_050", "level": "A1", "target": "open", "pl": "otwierać"},
    {"id": "en_a1_051", "level": "A1", "target": "close", "pl": "zamykać"},
    {"id": "en_a2_052", "level": "A2", "target": "arrive", "pl": "przyjeżdżać / przybywać"},
    {"id": "en_a2_053", "level": "A2", "target": "leave", "pl": "wyjeżdżać / opuszczać"},
    {"id": "en_a2_054", "level": "A2", "target": "borrow", "pl": "pożyczać od kogoś"},
    {"id": "en_a2_055", "level": "A2", "target": "lend", "pl": "pożyczać komuś"},
    {"id": "en_a2_056", "level": "A2", "target": "choose", "pl": "wybierać"},
    {"id": "en_a2_057", "level": "A2", "target": "decide", "pl": "decydować"},
    {"id": "en_a2_058", "level": "A2", "target": "explain", "pl": "wyjaśniać"},
    {"id": "en_a2_059", "level": "A2", "target": "forget", "pl": "zapominać"},
    {"id": "en_a2_060", "level": "A2", "target": "remember", "pl": "pamiętać"},
    {"id": "en_a2_061", "level": "A2", "target": "invite", "pl": "zapraszać"},
    {"id": "en_a2_062", "level": "A2", "target": "meet", "pl": "spotykać"},
    {"id": "en_a2_063", "level": "A2", "target": "move", "pl": "przeprowadzać się / poruszać"},
    {"id": "en_a2_064", "level": "A2", "target": "order", "pl": "zamawiać"},
    {"id": "en_a2_065", "level": "A2", "target": "plan", "pl": "planować"},
    {"id": "en_a2_066", "level": "A2", "target": "repair", "pl": "naprawiać"},
    {"id": "en_a2_067", "level": "A2", "target": "return", "pl": "wracać / zwracać"},
    {"id": "en_a2_068", "level": "A2", "target": "send", "pl": "wysyłać"},
    {"id": "en_a2_069", "level": "A2", "target": "spend", "pl": "wydawać / spędzać"},
    {"id": "en_a2_070", "level": "A2", "target": "stay", "pl": "zostawać"},
    {"id": "en_a2_071", "level": "A2", "target": "travel", "pl": "podróżować"},
    {"id": "en_a2_072", "level": "A2", "target": "wait", "pl": "czekać"},
    {"id": "en_a2_073", "level": "A2", "target": "wear", "pl": "nosić"},
    {"id": "en_a2_074", "level": "A2", "target": "weather", "pl": "pogoda"},
    {"id": "en_a2_075", "level": "A2", "target": "journey", "pl": "podróż"},
    {"id": "en_a2_076", "level": "A2", "target": "appointment", "pl": "spotkanie / wizyta"},
    {"id": "en_a2_077", "level": "A2", "target": "neighbour", "pl": "sąsiad"},
    {"id": "en_a2_078", "level": "A2", "target": "quiet", "pl": "cichy"},
    {"id": "en_a2_079", "level": "A2", "target": "busy", "pl": "zajęty"},
    {"id": "en_a2_080", "level": "A2", "target": "early", "pl": "wcześnie"},
    {"id": "en_a2_081", "level": "A2", "target": "late", "pl": "późno"},
    {"id": "en_a2_082", "level": "A2", "target": "enough", "pl": "wystarczająco"},
    {"id": "en_a2_083", "level": "A2", "target": "usually", "pl": "zwykle"},
    {"id": "en_a2_084", "level": "A2", "target": "sometimes", "pl": "czasami"},
    {"id": "en_a2_085", "level": "A2", "target": "already", "pl": "już"},
    {"id": "en_a2_086", "level": "A2", "target": "still", "pl": "nadal"},
    {"id": "en_a2_087", "level": "A2", "target": "almost", "pl": "prawie"},
    {"id": "en_a2_088", "level": "A2", "target": "perhaps", "pl": "być może"},
    {"id": "en_a2_089", "level": "A2", "target": "because", "pl": "ponieważ"},
    {"id": "en_a2_090", "level": "A2", "target": "although", "pl": "chociaż"},
    {"id": "en_a2_091", "level": "A2", "target": "during", "pl": "podczas"},
    {"id": "en_a2_092", "level": "A2", "target": "without", "pl": "bez"},
    {"id": "en_a2_093", "level": "A2", "target": "instead", "pl": "zamiast"},
    {"id": "en_b1_094", "level": "B1", "target": "achieve", "pl": "osiągać"},
    {"id": "en_b1_095", "level": "B1", "target": "admit", "pl": "przyznawać"},
    {"id": "en_b1_096", "level": "B1", "target": "avoid", "pl": "unikać"},
    {"id": "en_b1_097", "level": "B1", "target": "behave", "pl": "zachowywać się"},
    {"id": "en_b1_098", "level": "B1", "target": "compare", "pl": "porównywać"},
    {"id": "en_b1_099", "level": "B1", "target": "complain", "pl": "skarżyć się"},
    {"id": "en_b1_100", "level": "B1", "target": "consider", "pl": "rozważać"},
    {"id": "en_b1_101", "level": "B1", "target": "depend", "pl": "zależeć"},
    {"id": "en_b1_102", "level": "B1", "target": "develop", "pl": "rozwijać"},
    {"id": "en_b1_103", "level": "B1", "target": "expect", "pl": "oczekiwać"},
    {"id": "en_b1_104", "level": "B1", "target": "improve", "pl": "poprawiać / ulepszać"},
    {"id": "en_b1_105", "level": "B1", "target": "increase", "pl": "zwiększać"},
    {"id": "en_b1_106", "level": "B1", "target": "manage", "pl": "dawać sobie radę / zarządzać"},
    {"id": "en_b1_107", "level": "B1", "target": "notice", "pl": "zauważać"},
    {"id": "en_b1_108", "level": "B1", "target": "offer", "pl": "oferować"},
    {"id": "en_b1_109", "level": "B1", "target": "provide", "pl": "zapewniać"},
    {"id": "en_b1_110", "level": "B1", "target": "realise", "pl": "uświadamiać sobie"},
    {"id": "en_b1_111", "level": "B1", "target": "recommend", "pl": "polecać"},
    {"id": "en_b1_112", "level": "B1", "target": "reduce", "pl": "zmniejszać"},
    {"id": "en_b1_113", "level": "B1", "target": "refuse", "pl": "odmawiać"},
    {"id": "en_b1_114", "level": "B1", "target": "require", "pl": "wymagać"},
    {"id": "en_b1_115", "level": "B1", "target": "seem", "pl": "wydawać się"},
    {"id": "en_b1_116", "level": "B1", "target": "suggest", "pl": "sugerować"},
    {"id": "en_b1_117", "level": "B1", "target": "support", "pl": "wspierać"},
    {"id": "en_b1_118", "level": "B1", "target": "experience", "pl": "doświadczenie"},
    {"id": "en_b1_119", "level": "B1", "target": "advantage", "pl": "zaleta"},
    {"id": "en_b1_120", "level": "B1", "target": "disadvantage", "pl": "wada"},
    {"id": "en_b1_121", "level": "B1", "target": "decision", "pl": "decyzja"},
    {"id": "en_b1_122", "level": "B1", "target": "environment", "pl": "środowisko"},
    {"id": "en_b1_123", "level": "B1", "target": "opportunity", "pl": "okazja / możliwość"},
    {"id": "en_b1_124", "level": "B1", "target": "relationship", "pl": "relacja"},
    {"id": "en_b1_125", "level": "B1", "target": "responsibility", "pl": "odpowiedzialność"},
    {"id": "en_b1_126", "level": "B1", "target": "solution", "pl": "rozwiązanie"},
    {"id": "en_b1_127", "level": "B1", "target": "successful", "pl": "udany / odnoszący sukces"},
    {"id": "en_b1_128", "level": "B1", "target": "likely", "pl": "prawdopodobny"},
    {"id": "en_b1_129", "level": "B1", "target": "available", "pl": "dostępny"},
    {"id": "en_b1_130", "level": "B1", "target": "necessary", "pl": "konieczny"},
    {"id": "en_b1_131", "level": "B1", "target": "recent", "pl": "niedawny"},
    {"id": "en_b1_132", "level": "B1", "target": "instead of", "pl": "zamiast"},
    {"id": "en_b1_133", "level": "B1", "target": "as soon as", "pl": "jak tylko"},
    {"id": "en_b2_134", "level": "B2", "target": "acknowledge", "pl": "uznawać / przyznawać"},
    {"id": "en_b2_135", "level": "B2", "target": "assume", "pl": "zakładać"},
    {"id": "en_b2_136", "level": "B2", "target": "convince", "pl": "przekonywać"},
    {"id": "en_b2_137", "level": "B2", "target": "decline", "pl": "odmawiać / spadać"},
    {"id": "en_b2_138", "level": "B2", "target": "demonstrate", "pl": "wykazywać / demonstrować"},
    {"id": "en_b2_139", "level": "B2", "target": "emphasise", "pl": "podkreślać"},
    {"id": "en_b2_140", "level": "B2", "target": "encounter", "pl": "napotykać"},
    {"id": "en_b2_141", "level": "B2", "target": "ensure", "pl": "zapewniać"},
    {"id": "en_b2_142", "level": "B2", "target": "establish", "pl": "ustanawiać / ustalać"},
    {"id": "en_b2_143", "level": "B2", "target": "evaluate", "pl": "oceniać"},
    {"id": "en_b2_144", "level": "B2", "target": "maintain", "pl": "utrzymywać"},
    {"id": "en_b2_145", "level": "B2", "target": "negotiate", "pl": "negocjować"},
    {"id": "en_b2_146", "level": "B2", "target": "overcome", "pl": "przezwyciężać"},
    {"id": "en_b2_147", "level": "B2", "target": "persuade", "pl": "przekonywać"},
    {"id": "en_b2_148", "level": "B2", "target": "prevent", "pl": "zapobiegać"},
    {"id": "en_b2_149", "level": "B2", "target": "recognise", "pl": "rozpoznawać / uznawać"},
    {"id": "en_b2_150", "level": "B2", "target": "regardless", "pl": "niezależnie"},
    {"id": "en_b2_151", "level": "B2", "target": "reliable", "pl": "niezawodny / wiarygodny"},
    {"id": "en_b2_152", "level": "B2", "target": "significant", "pl": "znaczący"},
    {"id": "en_b2_153", "level": "B2", "target": "sufficient", "pl": "wystarczający"},
    {"id": "en_b2_154", "level": "B2", "target": "therefore", "pl": "dlatego / zatem"},
    {"id": "en_b2_155", "level": "B2", "target": "whereas", "pl": "podczas gdy"},
    {"id": "en_b2_156", "level": "B2", "target": "nevertheless", "pl": "niemniej jednak"},
    {"id": "en_b2_157", "level": "B2", "target": "consequently", "pl": "w konsekwencji"},
    {"id": "en_b2_158", "level": "B2", "target": "approach", "pl": "podejście"},
    {"id": "en_b2_159", "level": "B2", "target": "awareness", "pl": "świadomość"},
    {"id": "en_b2_160", "level": "B2", "target": "circumstance", "pl": "okoliczność"},
    {"id": "en_b2_161", "level": "B2", "target": "commitment", "pl": "zaangażowanie"},
    {"id": "en_b2_162", "level": "B2", "target": "consequence", "pl": "konsekwencja"},
    {"id": "en_b2_163", "level": "B2", "target": "evidence", "pl": "dowód / materiał dowodowy"},
    {"id": "en_b2_164", "level": "B2", "target": "impact", "pl": "wpływ"},
    {"id": "en_b2_165", "level": "B2", "target": "issue", "pl": "kwestia / problem"},
    {"id": "en_b2_166", "level": "B2", "target": "outcome", "pl": "wynik / rezultat"},
    {"id": "en_b2_167", "level": "B2", "target": "perspective", "pl": "perspektywa"},
    {"id": "en_b2_168", "level": "B2", "target": "requirement", "pl": "wymóg"},
    {"id": "en_b2_169", "level": "B2", "target": "shortage", "pl": "niedobór"},
    {"id": "en_b2_170", "level": "B2", "target": "tendency", "pl": "tendencja"},
    {"id": "en_b2_171", "level": "B2", "target": "workload", "pl": "obciążenie pracą"}
  ]
};
